[build-system]
requires = [ "setuptools>=40.6.0", "wheel>=0.34.2",]
build-backend = "setuptools.build_meta"

[project]
name = "pytest-mypy-plugins-shim"
version = "0.1.0"
description = "Substitute for \"pytest-mypy-plugins\" for Python implementations which aren't supported by mypy."
readme = "README.rst"
keywords = []
dynamic = [ "requires-python", "classifiers", "dependencies",]

[[project.authors]]
email = "dominic@davis-foster.co.uk"
name = "Dominic Davis-Foster"


[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/python-coincidence/pytest-mypy-plugins-shim"
"Issue Tracker" = "https://github.com/python-coincidence/pytest-mypy-plugins-shim/issues"
"Source Code" = "https://github.com/python-coincidence/pytest-mypy-plugins-shim"

[tool.importcheck]
always = ["pytest_mypy_plugins_shim"]

[project.entry-points.pytest11]
pytest-mypy-plugins-shim = "pytest_mypy_plugins_shim"
